---
title: "ElectricityData"
output: html_document
---

```{r setup, include=FALSE}
electricity <- read_excel("Desktop/Monthly-hourly-load-values_2006-2015.xlsx")
electricity <-electricity %>% select(-`Coverage ratio`)
austria <-electricity %>% subset(Country=="AT") %>% select(-"Country")

toDate <- function(year, month, day) {
    ISOdate(year, month, day)
}



electricity$date <-toDate (electricity$Year,electricity$Month,electricity$Day)


austria<- gather(austria, hour, demand, '0':'23', factor_key=FALSE)

austria <-austria %>% select(-date)

electricity <- gather(electricity, hour, demand, '0':'23', factor_key=FALSE)

electricity <-electricity %>% select(-date)

romania <-electricity %>% subset(Country=="RO")




romania2 <-romania2 %>% select(CountryCode,Year,Month,Day,Hour,Value)

romania3$Day <-day(romania3$DateShort)

romania2 <- read_excel("Desktop/MHLV_data-2015-2017.xlsx",sheet = "2015-2017")
romania2 <-romania2 %>% subset(CountryCode=="RO")
romania2$Hour <-hour(romania2$TimeFrom)
romania2$Day <-day(romania2$DateShort)
romania2 <-romania2 %>% select(CountryCode,Year,Month,Day,Hour,Value)



romania3 <- read_excel("Desktop/MHLV_data-2015-2017.xlsx",sheet = "2018-2019")
romania3 <-romania3 %>% subset(CountryCode=="RO")
romania3$Day <-day(romania3$DateShort)
romania3$Hour <-hour(romania3$TimeFrom)
romania3 <-romania3 %>% select(CountryCode,Year,Month,Day,Hour,Value)

romania <-romania %>% select(-Country)
romania2 <-romania2 %>% select(-CountryCode)
romania3 <-romania3 %>% select(-CountryCode)

romania  <- sapply( romania , as.numeric )
romania2  <- sapply( romania2 , as.numeric )
romania3  <- sapply( romania3 , as.numeric )

romania <-as.data.frame(romania)
romania <-romania %>% rename(Value=demand, Hour=hour)
romania2 <-as.data.frame(romania2)
romania3 <-as.data.frame(romania3)

romania_EDF  <- merge(romania, romania2, all = TRUE) %>% merge(romania3, all = TRUE)

save(romania,file="Romania.rda")
x <- import("Romania.rda")
convert("RomaniaEDF.rda", "RomaniaEDF.xlsx")

save(austria,file="austria.rda")
x <- import("austria.rda")
convert("austria.rda", "austria.xlsx")

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
